- NutMyProblemUnity/Assets/Resources/Animations/Prinz von Walnut Ausgangssituation farbe.controller
- NutMyProblemUnity/Assets/playerAnimationController.cs
animation was added with NUT-40
> integrated substitute idle animation

- NutMyProblemUnity/Assets/NutMyProblem.inputactions
- NutMyProblemUnity/Assets/NutMyProblem.inputactions.meta
- NutMyProblemUnity/Assets/Resources/prefabs/Player.prefab
- NutMyProblemUnity/Assets/playerAnimationController.cs
- NutMyProblemUnity/Assets/playerController.cs
- NutMyProblemUnity/Packages/manifest.json
- NutMyProblemUnity/Packages/packages-lock.json
- NutMyProblemUnity/ProjectSettings/ProjectSettings.asset
Switched to new Unity Input System
> NUT-46 player movement rework

- NutMyProblemUnity/Assets/EnemyController.cs
- NutMyProblemUnity/Assets/GameManager.cs
- NutMyProblemUnity/Assets/Resources/Sprites/commonkught.png.meta
- NutMyProblemUnity/Assets/Resources/prefabs/commonkught.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/commonkught.prefab.meta
- NutMyProblemUnity/Assets/Resources/prefabs/opossum.prefab
- NutMyProblemUnity/Packages/manifest.json
- NutMyProblemUnity/Packages/packages-lock.json
- NutMyProblemUnity/ProjectSettings/ProjectVersion.txt
- Vor- und Zurückbewegung von Gegnern im EnemyController.
- Erstellen von Commonkught-Prefab mit Hitbox
> NUT-41-Gegner-Basics

- NutMyProblemUnity/Assets/Background.meta
- NutMyProblemUnity/Assets/Background/Hintergrund_Test.psd.meta
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
> NUT-13-Background

- NutMyProblemUnity/Assets/Weapons.cs
- NutMyProblemUnity/Assets/playerAnimationController.cs
changed playerAnimationController.cs so animations for gloves and bow can be implemented easily
> prepared code for new animations

- NutMyProblemUnity/Assets/Weapons.cs
- NutMyProblemUnity/Assets/playerAnimationController.cs
Fists and Gloves are copies of the sword for now, should be changed later
> NUT-63 Added Fists and Gloves

- NutMyProblemUnity/Assets/Resources/prefabs/Player.prefab
- NutMyProblemUnity/Assets/playerAnimationController.cs
-Fixed animations not playing correctly
-Added fist animations
> NUT-112 Animation Fixes

- NutMyProblemUnity/Assets/InputSettings.inputactions
- NutMyProblemUnity/Assets/Resources/prefabs/Player.prefab
- NutMyProblemUnity/Assets/Scripts/playerAnimationController.cs
- NutMyProblemUnity/Assets/Scripts/playerController.cs
- NutMyProblemUnity/Packages/manifest.json
- NutMyProblemUnity/Packages/packages-lock.json
- NutMyProblemUnity/ProjectSettings/ProjectVersion.txt
-Added dash function, cooldown, State.dashing
-Added controller support with InputActions
> NUT-132 Player Dash

- NutMyProblemUnity/Assets/Resources/prefabs/WeaponDrop.prefab
- NutMyProblemUnity/Assets/Scripts/EnemyController.cs
- NutMyProblemUnity/Assets/Scripts/GameManager.cs
- NutMyProblemUnity/Assets/Scripts/WeaponDropManager.cs
Gegner lässt seine Waffe fallen, wenn dieser zerstört wird.
Zuweisung des richtigen Waffentyps.
> NUT-67_EnemyDrops

- NutMyProblemUnity/Assets/InputSettings.inputactions
- NutMyProblemUnity/Assets/Resources/prefabs/Player.prefab
- NutMyProblemUnity/Assets/Scripts/playerAnimationController.cs
- NutMyProblemUnity/Assets/Scripts/playerController.cs
-removed Input Event
-removed State in playerAnimationController
-increased default walk speed
-fixed NUT-159
> NUT-168, NUT-159 Removed Sprint

- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Animations.controller
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Animations.controller.meta
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Attack_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Attack_Animation.anim.meta
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Damaged_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Damaged_Animation.anim.meta
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Idle_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Hazardnut_Idle_Animation.anim.meta
- NutMyProblemUnity/Assets/Resources/prefabs/Hazardnut.prefab
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
- NutMyProblemUnity/Assets/Scripts/DamageHandler.cs
- NutMyProblemUnity/Assets/Scripts/HazardnutAnimationController.cs
- NutMyProblemUnity/Assets/Scripts/HazardnutAnimationController.cs.meta
- NutMyProblemUnity/Assets/Scripts/playerAnimationController.cs
- NutMyProblemUnity/Packages/manifest.json
- NutMyProblemUnity/Packages/packages-lock.json
-Added HazardnutAnimationController
-Sprites have to be flipped
-needs small rework after enemy script rework
> NUT-210 Implemented Hazardnut Animations

- NutMyProblemUnity/Assets/Resources/prefabs/Player.prefab
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
-Made player light larger
-Made global light dimmer
> Ligthing Updates

- NutMyProblemUnity/Assets/Resources/prefabs/DeathBarrier.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/DeathBarrier.prefab.meta
- NutMyProblemUnity/Assets/Scripts/ColliderScript.cs
- NutMyProblemUnity/Assets/Scripts/GameManager.cs
- NutMyProblemUnity/Assets/Scripts/HazardnutAnimationController.cs
- NutMyProblemUnity/Assets/Scripts/playerController.cs
- NutMyProblemUnity/ProjectSettings/TagManager.asset
-Added a death barrier that follows the player below the map and reloads the scene if the player touches it
-Fixed issue in ColliderScript()
> NUT-229 Death Barrier

- NutMyProblemUnity/Assets/Physics.meta
- NutMyProblemUnity/Assets/Physics/CameraPushBoxMat.physicsMaterial2D
- NutMyProblemUnity/Assets/Physics/CameraPushBoxMat.physicsMaterial2D.meta
- NutMyProblemUnity/Assets/Resources/prefabs/CameraPushBox.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/CameraPushBox.prefab.meta
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Platform.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Platform_EndPiece.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Platform_EndPiece_BW.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/Player.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/PlayerCamera.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/PlayerCamera.prefab.meta
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
- NutMyProblemUnity/Assets/Scripts/CameraManager.cs
- NutMyProblemUnity/Assets/Scripts/playerController.cs
- NutMyProblemUnity/ProjectSettings/Physics2DSettings.asset
- NutMyProblemUnity/ProjectSettings/TagManager.asset
-Camera follows a box that gets pushed by the player
-Smooth acceleration of camera with MoveTowards()
> NUT-82 Camera Movement

- NutMyProblemUnity/Assets/Scripts/ColliderScript.cs
- NutMyProblemUnity/Assets/Scripts/playerController.cs
-Reworked the dash to not freeze position.y and instead stop velocity.y
-1/3 gravity while dashing
> NUT-225 Dash Rework

- NutMyProblemUnity/Assets/ForegroundObjectController.cs
- NutMyProblemUnity/Assets/ForegroundObjectController.cs.meta
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Foreground_Object.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Foreground_Object.prefab.meta
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
- NutMyProblemUnity/Assets/Scripts/playerController.cs
-Added empty that moves its child object for a parallax effect
-Has checks for zero and more than one children
> NUT-244 Foreground Parallax

- NutMyProblemUnity/Assets/Resources/prefabs/Level/Chandelier.prefab
-fixed light not moving with the chandelier by making it a child of the chandelier
> NUT-250 Chandelier Light Fix

- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
- NutMyProblemUnity/Assets/Scripts/playerController.cs
-Fixed start position of the raycast that descides which platform the shadow sould snap to, now the shadow only snaps to a platform if the player will land on it
> NUT-253 Player Shadow Fix

- NutMyProblemUnity/Assets/Resources/Animations/CommonKnught_Walk_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Player_Gloves_Fall_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Player_Sword_Fall_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Player_WithoutWeapon_Fall_Animation.anim
- NutMyProblemUnity/Assets/Resources/Animations/Prinz von Walnut Ausgangssituation farbe.controller
the clips for the fall animation weren't saved so I forgot to commit them
> NUT-252 Animation Clips

- NutMyProblemUnity/Assets/Resources/prefabs/PlayerCamera.prefab
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
- NutMyProblemUnity/Assets/Scripts/CameraManager.cs
-Bugfixing
-Added Comments
-Changed structure for better readability
> NUT-266 Camera Code Cleanup

- NutMyProblemUnity/Assets/BackgroundObjectController.cs
- NutMyProblemUnity/Assets/BackgroundObjectController.cs.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Attack1.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Attack2.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Attack3.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Defeat1.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Defeat2.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Idle1.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Idle2.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Idle3.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Walk1.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Walk2.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Walk3.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Walk4.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Walk5.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/CommonKnught_Walk6.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run1.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run2.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run3.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run4.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run5.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run6.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run7.png.meta
- NutMyProblemUnity/Assets/Resources/Sprites/Player_WithoutWeapon_Run8.png.meta
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Background_Object.prefab
- NutMyProblemUnity/Assets/Resources/prefabs/Level/Background_Object.prefab.meta
- NutMyProblemUnity/Assets/Scenes/SampleScene.unity
-Added empty for background parallax
-Fixed scale of some animations
> NUT-280 Background Empty
